FROM php:fpm

# Install dependencies sistem
RUN apt-get update && apt-get install -y \
    libicu-dev libzip-dev libpng-dev libjpeg-dev libjpeg62-turbo-dev \
    libfreetype6-dev libonig-dev libxml2-dev pkg-config libpq-dev \
    zip unzip curl git ca-certificates openssl \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

# Core extensions
# 1. Configure Extensions
RUN docker-php-ext-configure gd --with-freetype --with-jpeg \
    && docker-php-ext-configure intl

# 2. Install Extensions
RUN docker-php-ext-install -j$(nproc) \
    gd intl mbstring zip pdo pdo_pgsql pgsql xml bcmath exif

# Optional: install terpisah jika perlu
# RUN docker-php-ext-install opcache || true

# Enable opcache via config file (workaround PHP 8.5 bug)
RUN echo "opcache.enable=1" > /usr/local/etc/php/conf.d/opcache.ini \
    && echo "opcache.memory_consumption=128" >> /usr/local/etc/php/conf.d/opcache.ini \
    && echo "opcache.interned_strings_buffer=8" >> /usr/local/etc/php/conf.d/opcache.ini \
    && echo "opcache.max_accelerated_files=4000" >> /usr/local/etc/php/conf.d/opcache.ini

# Install Composer (direkomendasikan untuk dependency management)
RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer

# Buat folder untuk menyimpan sertifikat SSL (jika diperlukan)
RUN mkdir -p /etc/nginx/ssl

# Generate self-signed SSL certificate otomatis saat build (opsional)
RUN openssl req -x509 -nodes -days 365 \
    -subj "/C=ID/ST=Jakarta/L=Jakarta/O=KoiN-CoDeveloper/CN=localhost" \
    -newkey rsa:2048 \
    -keyout /etc/nginx/ssl/localhost.key \
    -out /etc/nginx/ssl/localhost.crt

# Copy konfigurasi php.ini khusus (opsional, bisa juga mount volume di docker-compose)
# COPY ./php.ini /usr/local/etc/php/

# Copy konfigurasi PHP-FPM pool jika ingin custom (opsional, bisa juga mount volume di docker-compose)
# COPY ./www.conf /usr/local/etc/php-fpm.d/www.conf

# Copy source code aplikasi (opsional, bisa juga mount volume di docker-compose)
# COPY ./phpapp /var/www/html

# Tambah untuk production (Optional)
ENV PHP_OPCACHE_ENABLE=1
ENV PHP_MEMORY_LIMIT=256M

# Set working directory
WORKDIR /var/www/html

# Set permission jika perlu
# RUN chown -R www-data:www-data /var/www/html

# Set permission log (Optional)
RUN mkdir -p /var/log/php-fpm && chown -R www-data:www-data /var/log/php-fpm

# Fix PHP-FPM socket error
RUN mkdir -p /var/run/php && \
    chown -R www-data:www-data /var/run/php && \
    chmod 777 /var/run/php

# Expose port FPM default
EXPOSE 9000
